project: dot
providers:
  google_secretmanager:
    env:
      AWS_ACCESS_KEY_ID:
        path: projects/vfarcic/secrets/aws-access-key-id/versions/5
      AWS_SECRET_ACCESS_KEY:
        path: projects/vfarcic/secrets/aws-secret-access-key/versions/5
      AWS_ACCOUNT_ID:
        path: projects/vfarcic/secrets/aws-account-id/versions/1
      AZURE_TENANT_ID:
        path: projects/vfarcic/secrets/azure-tenant/versions/1
