apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: dot-sql
  annotations:
    meta.crossplane.io/maintainer: Viktor Farcic (@vfarcic)
    meta.crossplane.io/source: github.com/vfarcic/crossplane-tutorial
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: Fully operational PostgreSQL databases in AWS, Google Cloud Platform, and Azure.
    meta.crossplane.io/readme: A Configuration package that defines a SQL and SQLClaim types that can be used to create and provision fully operational databases in AWS, Google Cloud Platform, and Azure.
spec:
  crossplane:
    version: ">=v1.14.0"
  dependsOn:
  - provider: xpkg.upbound.io/upbound/provider-aws-ec2
    version: ">=v1.0.0"
  - provider: xpkg.upbound.io/upbound/provider-aws-rds
    version: ">=v1.0.0"
  - provider: xpkg.upbound.io/upbound/provider-azure-dbforpostgresql
    version: ">=v0.33.0"
  - provider: xpkg.upbound.io/upbound/provider-gcp-sql
    version: ">=v0.33.0"
  - provider: xpkg.upbound.io/crossplane-contrib/provider-sql
    version: ">=v0.9.0"
  - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
    version: ">=v0.1.4"
  - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
    version: ">=v0.4.0"
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: ">=v0.2.1"
  # - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
  #   version: ">=v0.10.0"
